### ISSUE TITLE
HTML Parser doesn't work

### ISSUE THREAD

**Issue by Anjlo** [sodanakin/Anonymous_Scripter_Tool#2]
I'm not sure if it's just the parser that doesn't work, but it doesn't make a accounts.txt . Thanks for the tool mate, hope I can get it working to scan maps.

pokemonminer102@divismail.ru : letsmine123 - Ben Jones - 1978-04-07 - Denmark
First request...
C:\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
C:\Python27\lib\site-packages\requests\packages\urllib3\util\ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Second request...
Second worked!
Third request...
Last request...
Getting mail...
Attempt 1.
C:\Python27\lib\site-packages\bs4\__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 140 of the file anonymous_scripter.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
C:\Python27\lib\site-packages\bs4\builder\_htmlparser.py:170: RuntimeWarning: Python's built-in HTMLParser cannot parse the given document. This is not a bug in Beautiful Soup. The best solution is to install an external parser (lxml or html5lib), and use Beautiful Soup with that parser. See http://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser for help.
  "Python's built-in HTMLParser cannot parse the given document. This is not a bug in Beautiful Soup. The best solution is to install an external parser (lxml or html5lib), and use Beautiful Soup with that parser. See http://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser for help."))
Traceback (most recent call last):
  File "anonymous_scripter.py", line 140, in <module>
    bs = BeautifulSoup(mail[0]['mail_html'])
  File "C:\Python27\lib\site-packages\bs4\__init__.py", line 228, in __init__
    self._feed()
  File "C:\Python27\lib\site-packages\bs4\__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "C:\Python27\lib\site-packages\bs4\builder\_htmlparser.py", line 171, in feed
    raise e
HTMLParser.HTMLParseError: malformed start tag, at line 172, column 119

**Comment by sodanakin** [comment]
Hi this tool was originally made by Anonymous_Scripter on reddit. I just hosted it here so it wouldn't get lost (It was a pastebin originally) Sadly I don't have any Python experience and can't really add or solve issues =\
